### ISSUE TITLE
react-datepicker Module not found

### ISSUE THREAD

**Issue by MoeBuTa** [MoeBuTa/todoapp-ts#1]
I've installed @types/react-datepicker and correctly imported it. But the issue still persists:

Module not found: Error: Can't resolve 'react-datepicker' in 'D:\WebStorm 2023.2.5\projects\cfc\todoapp-ts\src\components'
ERROR in ./src/components/todo.tsx 7:0-42
Module not found: Error: Can't resolve 'react-datepicker' in 'D:\WebStorm 2023.2.5\projects\cfc\todoapp-ts\src\components'

**Comment by vasilvlyubenov** [comment]
Hello, @types/react-datepicker contains only type definitions for react-datepicker.
You also need to install and react-datepicker (npm i react-datepicker) and the problem should be resolved.

**Comment by MoeBuTa** [comment]
> Hello, @types/react-datepicker contains only type definitions for react-datepicker.
> 
> You also need to install and react-datepicker (npm i react-datepicker) and the problem should be resolved.

Thank you! Will try it out later.
